# https://github.com/pyenv/pyenv/wiki
case node[:platform]
when 'debian', 'ubuntu', 'mint'
  package "make"
  package "build-essential"
  package "libssl-dev"
  package "zlib1g-dev"
  package "libbz2-dev"
  package "libreadline-dev"
  package "libsqlite3-dev"
  package "wget"
  package "curl"
  package "llvm"
  package "libncurses5-dev"
  package "xz-utils"
  package "tk-dev"
  package "libxml2-dev"
  package "libxmlsec1-dev"
  package "libffi-dev"
  package "liblzma-dev"
when "osx", "darwin"
  package "openssl"
  package "readline"
  package "sqlite3"
  package "xz"
  package "zlib"
when 'redhat', 'fedora', 'amazon' # redhad includes CentOS
  package "make"
  package "gcc"
  package "zlib-devel"
  package "bzip2"
  package "bzip2-devel"
  package "readline-devel"
  package "sqlite"
  package "sqlite-devel"
  package "openssl-devel"
  package "tk-devel"
  package "libffi-devel"
end
